version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - .env
    depends_on:
      - db  

  db:
    image: postgres:16.3  
    ports:
      - "5432:5432" 
    env_file:
      - .env.local
    

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgre
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  # redis:
  #   image: redis
  #   command: /bin/sh -c "redis-server --requirepass REDIS_PASSWORD"
  #   environment:
  #     REDIS_PASSWORD: redis
  #     REDIS_URI : redis://default:${REDIS_PASSWORD}@redis:6379
  #   ports:
  #     - "6379:6379"
   
  #   volumes:
  #     - ./redis:/data:/data