version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db  

  db:
    image: postgres:16.3  
    ports:
      - "5432:5432" 
    env_file:
      - .env.local

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: postgres
  #     PGADMIN_DEFAULT_PASSWORD: postgre
  #   ports:
  #     - "5050:80"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
